# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Versus' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Versus
  pod 'SwiftyJSON', '~> 4.0'

  target 'VersusTests' do
    use_frameworks!
    inherit! :search_paths
    # Pods for testing
  end

  target 'VersusUITests' do
    use_frameworks!
    inherit! :search_paths
    # Pods for testing
  end
  
  pod 'Firebase/Core'
  pod 'Firebase/Database'

end
